// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laserscan.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_laserscan_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_laserscan_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common_header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_laserscan_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_laserscan_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_laserscan_2eproto;
namespace laserscan {
class laserscanpb;
struct laserscanpbDefaultTypeInternal;
extern laserscanpbDefaultTypeInternal _laserscanpb_default_instance_;
}  // namespace laserscan
PROTOBUF_NAMESPACE_OPEN
template<> ::laserscan::laserscanpb* Arena::CreateMaybeMessage<::laserscan::laserscanpb>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace laserscan {

// ===================================================================

class laserscanpb final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:laserscan.laserscanpb) */ {
 public:
  inline laserscanpb() : laserscanpb(nullptr) {}
  ~laserscanpb() override;
  explicit PROTOBUF_CONSTEXPR laserscanpb(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  laserscanpb(const laserscanpb& from);
  laserscanpb(laserscanpb&& from) noexcept
    : laserscanpb() {
    *this = ::std::move(from);
  }

  inline laserscanpb& operator=(const laserscanpb& from) {
    CopyFrom(from);
    return *this;
  }
  inline laserscanpb& operator=(laserscanpb&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const laserscanpb& default_instance() {
    return *internal_default_instance();
  }
  static inline const laserscanpb* internal_default_instance() {
    return reinterpret_cast<const laserscanpb*>(
               &_laserscanpb_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(laserscanpb& a, laserscanpb& b) {
    a.Swap(&b);
  }
  inline void Swap(laserscanpb* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(laserscanpb* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  laserscanpb* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<laserscanpb>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const laserscanpb& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const laserscanpb& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(laserscanpb* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "laserscan.laserscanpb";
  }
  protected:
  explicit laserscanpb(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRangesFieldNumber = 9,
    kIntensitiesFieldNumber = 10,
    kHeaderFieldNumber = 1,
    kAngleMinFieldNumber = 2,
    kAngleMaxFieldNumber = 3,
    kAngleIncrementFieldNumber = 4,
    kTimeIncrementFieldNumber = 5,
    kScanTimeFieldNumber = 6,
    kRangeMinFieldNumber = 7,
    kRangeMaxFieldNumber = 8,
  };
  // repeated float ranges = 9;
  int ranges_size() const;
  private:
  int _internal_ranges_size() const;
  public:
  void clear_ranges();
  private:
  float _internal_ranges(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_ranges() const;
  void _internal_add_ranges(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_ranges();
  public:
  float ranges(int index) const;
  void set_ranges(int index, float value);
  void add_ranges(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      ranges() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_ranges();

  // repeated float intensities = 10;
  int intensities_size() const;
  private:
  int _internal_intensities_size() const;
  public:
  void clear_intensities();
  private:
  float _internal_intensities(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_intensities() const;
  void _internal_add_intensities(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_intensities();
  public:
  float intensities(int index) const;
  void set_intensities(int index, float value);
  void add_intensities(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      intensities() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_intensities();

  // .common.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::common::Header& header() const;
  PROTOBUF_NODISCARD ::common::Header* release_header();
  ::common::Header* mutable_header();
  void set_allocated_header(::common::Header* header);
  private:
  const ::common::Header& _internal_header() const;
  ::common::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::common::Header* header);
  ::common::Header* unsafe_arena_release_header();

  // float angle_min = 2;
  void clear_angle_min();
  float angle_min() const;
  void set_angle_min(float value);
  private:
  float _internal_angle_min() const;
  void _internal_set_angle_min(float value);
  public:

  // float angle_max = 3;
  void clear_angle_max();
  float angle_max() const;
  void set_angle_max(float value);
  private:
  float _internal_angle_max() const;
  void _internal_set_angle_max(float value);
  public:

  // float angle_increment = 4;
  void clear_angle_increment();
  float angle_increment() const;
  void set_angle_increment(float value);
  private:
  float _internal_angle_increment() const;
  void _internal_set_angle_increment(float value);
  public:

  // float time_increment = 5;
  void clear_time_increment();
  float time_increment() const;
  void set_time_increment(float value);
  private:
  float _internal_time_increment() const;
  void _internal_set_time_increment(float value);
  public:

  // float scan_time = 6;
  void clear_scan_time();
  float scan_time() const;
  void set_scan_time(float value);
  private:
  float _internal_scan_time() const;
  void _internal_set_scan_time(float value);
  public:

  // float range_min = 7;
  void clear_range_min();
  float range_min() const;
  void set_range_min(float value);
  private:
  float _internal_range_min() const;
  void _internal_set_range_min(float value);
  public:

  // float range_max = 8;
  void clear_range_max();
  float range_max() const;
  void set_range_max(float value);
  private:
  float _internal_range_max() const;
  void _internal_set_range_max(float value);
  public:

  // @@protoc_insertion_point(class_scope:laserscan.laserscanpb)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > ranges_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > intensities_;
  ::common::Header* header_;
  float angle_min_;
  float angle_max_;
  float angle_increment_;
  float time_increment_;
  float scan_time_;
  float range_min_;
  float range_max_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_laserscan_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// laserscanpb

// .common.Header header = 1;
inline bool laserscanpb::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool laserscanpb::has_header() const {
  return _internal_has_header();
}
inline const ::common::Header& laserscanpb::_internal_header() const {
  const ::common::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::common::Header&>(
      ::common::_Header_default_instance_);
}
inline const ::common::Header& laserscanpb::header() const {
  // @@protoc_insertion_point(field_get:laserscan.laserscanpb.header)
  return _internal_header();
}
inline void laserscanpb::unsafe_arena_set_allocated_header(
    ::common::Header* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:laserscan.laserscanpb.header)
}
inline ::common::Header* laserscanpb::release_header() {
  
  ::common::Header* temp = header_;
  header_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::common::Header* laserscanpb::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:laserscan.laserscanpb.header)
  
  ::common::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::common::Header* laserscanpb::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::Header>(GetArenaForAllocation());
    header_ = p;
  }
  return header_;
}
inline ::common::Header* laserscanpb::mutable_header() {
  ::common::Header* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:laserscan.laserscanpb.header)
  return _msg;
}
inline void laserscanpb::set_allocated_header(::common::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header));
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:laserscan.laserscanpb.header)
}

// float angle_min = 2;
inline void laserscanpb::clear_angle_min() {
  angle_min_ = 0;
}
inline float laserscanpb::_internal_angle_min() const {
  return angle_min_;
}
inline float laserscanpb::angle_min() const {
  // @@protoc_insertion_point(field_get:laserscan.laserscanpb.angle_min)
  return _internal_angle_min();
}
inline void laserscanpb::_internal_set_angle_min(float value) {
  
  angle_min_ = value;
}
inline void laserscanpb::set_angle_min(float value) {
  _internal_set_angle_min(value);
  // @@protoc_insertion_point(field_set:laserscan.laserscanpb.angle_min)
}

// float angle_max = 3;
inline void laserscanpb::clear_angle_max() {
  angle_max_ = 0;
}
inline float laserscanpb::_internal_angle_max() const {
  return angle_max_;
}
inline float laserscanpb::angle_max() const {
  // @@protoc_insertion_point(field_get:laserscan.laserscanpb.angle_max)
  return _internal_angle_max();
}
inline void laserscanpb::_internal_set_angle_max(float value) {
  
  angle_max_ = value;
}
inline void laserscanpb::set_angle_max(float value) {
  _internal_set_angle_max(value);
  // @@protoc_insertion_point(field_set:laserscan.laserscanpb.angle_max)
}

// float angle_increment = 4;
inline void laserscanpb::clear_angle_increment() {
  angle_increment_ = 0;
}
inline float laserscanpb::_internal_angle_increment() const {
  return angle_increment_;
}
inline float laserscanpb::angle_increment() const {
  // @@protoc_insertion_point(field_get:laserscan.laserscanpb.angle_increment)
  return _internal_angle_increment();
}
inline void laserscanpb::_internal_set_angle_increment(float value) {
  
  angle_increment_ = value;
}
inline void laserscanpb::set_angle_increment(float value) {
  _internal_set_angle_increment(value);
  // @@protoc_insertion_point(field_set:laserscan.laserscanpb.angle_increment)
}

// float time_increment = 5;
inline void laserscanpb::clear_time_increment() {
  time_increment_ = 0;
}
inline float laserscanpb::_internal_time_increment() const {
  return time_increment_;
}
inline float laserscanpb::time_increment() const {
  // @@protoc_insertion_point(field_get:laserscan.laserscanpb.time_increment)
  return _internal_time_increment();
}
inline void laserscanpb::_internal_set_time_increment(float value) {
  
  time_increment_ = value;
}
inline void laserscanpb::set_time_increment(float value) {
  _internal_set_time_increment(value);
  // @@protoc_insertion_point(field_set:laserscan.laserscanpb.time_increment)
}

// float scan_time = 6;
inline void laserscanpb::clear_scan_time() {
  scan_time_ = 0;
}
inline float laserscanpb::_internal_scan_time() const {
  return scan_time_;
}
inline float laserscanpb::scan_time() const {
  // @@protoc_insertion_point(field_get:laserscan.laserscanpb.scan_time)
  return _internal_scan_time();
}
inline void laserscanpb::_internal_set_scan_time(float value) {
  
  scan_time_ = value;
}
inline void laserscanpb::set_scan_time(float value) {
  _internal_set_scan_time(value);
  // @@protoc_insertion_point(field_set:laserscan.laserscanpb.scan_time)
}

// float range_min = 7;
inline void laserscanpb::clear_range_min() {
  range_min_ = 0;
}
inline float laserscanpb::_internal_range_min() const {
  return range_min_;
}
inline float laserscanpb::range_min() const {
  // @@protoc_insertion_point(field_get:laserscan.laserscanpb.range_min)
  return _internal_range_min();
}
inline void laserscanpb::_internal_set_range_min(float value) {
  
  range_min_ = value;
}
inline void laserscanpb::set_range_min(float value) {
  _internal_set_range_min(value);
  // @@protoc_insertion_point(field_set:laserscan.laserscanpb.range_min)
}

// float range_max = 8;
inline void laserscanpb::clear_range_max() {
  range_max_ = 0;
}
inline float laserscanpb::_internal_range_max() const {
  return range_max_;
}
inline float laserscanpb::range_max() const {
  // @@protoc_insertion_point(field_get:laserscan.laserscanpb.range_max)
  return _internal_range_max();
}
inline void laserscanpb::_internal_set_range_max(float value) {
  
  range_max_ = value;
}
inline void laserscanpb::set_range_max(float value) {
  _internal_set_range_max(value);
  // @@protoc_insertion_point(field_set:laserscan.laserscanpb.range_max)
}

// repeated float ranges = 9;
inline int laserscanpb::_internal_ranges_size() const {
  return ranges_.size();
}
inline int laserscanpb::ranges_size() const {
  return _internal_ranges_size();
}
inline void laserscanpb::clear_ranges() {
  ranges_.Clear();
}
inline float laserscanpb::_internal_ranges(int index) const {
  return ranges_.Get(index);
}
inline float laserscanpb::ranges(int index) const {
  // @@protoc_insertion_point(field_get:laserscan.laserscanpb.ranges)
  return _internal_ranges(index);
}
inline void laserscanpb::set_ranges(int index, float value) {
  ranges_.Set(index, value);
  // @@protoc_insertion_point(field_set:laserscan.laserscanpb.ranges)
}
inline void laserscanpb::_internal_add_ranges(float value) {
  ranges_.Add(value);
}
inline void laserscanpb::add_ranges(float value) {
  _internal_add_ranges(value);
  // @@protoc_insertion_point(field_add:laserscan.laserscanpb.ranges)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
laserscanpb::_internal_ranges() const {
  return ranges_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
laserscanpb::ranges() const {
  // @@protoc_insertion_point(field_list:laserscan.laserscanpb.ranges)
  return _internal_ranges();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
laserscanpb::_internal_mutable_ranges() {
  return &ranges_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
laserscanpb::mutable_ranges() {
  // @@protoc_insertion_point(field_mutable_list:laserscan.laserscanpb.ranges)
  return _internal_mutable_ranges();
}

// repeated float intensities = 10;
inline int laserscanpb::_internal_intensities_size() const {
  return intensities_.size();
}
inline int laserscanpb::intensities_size() const {
  return _internal_intensities_size();
}
inline void laserscanpb::clear_intensities() {
  intensities_.Clear();
}
inline float laserscanpb::_internal_intensities(int index) const {
  return intensities_.Get(index);
}
inline float laserscanpb::intensities(int index) const {
  // @@protoc_insertion_point(field_get:laserscan.laserscanpb.intensities)
  return _internal_intensities(index);
}
inline void laserscanpb::set_intensities(int index, float value) {
  intensities_.Set(index, value);
  // @@protoc_insertion_point(field_set:laserscan.laserscanpb.intensities)
}
inline void laserscanpb::_internal_add_intensities(float value) {
  intensities_.Add(value);
}
inline void laserscanpb::add_intensities(float value) {
  _internal_add_intensities(value);
  // @@protoc_insertion_point(field_add:laserscan.laserscanpb.intensities)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
laserscanpb::_internal_intensities() const {
  return intensities_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
laserscanpb::intensities() const {
  // @@protoc_insertion_point(field_list:laserscan.laserscanpb.intensities)
  return _internal_intensities();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
laserscanpb::_internal_mutable_intensities() {
  return &intensities_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
laserscanpb::mutable_intensities() {
  // @@protoc_insertion_point(field_mutable_list:laserscan.laserscanpb.intensities)
  return _internal_mutable_intensities();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace laserscan

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_laserscan_2eproto
